---
title: "Term Structure in High Frequency"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
        number_sections: FALSE
        df_print: kable
        css: style.css
        code_folding: hide
---

```{r knitr_setup, include=FALSE}
knitr::opts_chunk$set(
  warning=FALSE,
  message=FALSE,
  fig.width=8,
  fig.height=10
)
```


```{r script_setup}
library(data.table)
library(ggplot2)
library(magrittr)
library(extrafont)
library(scales)
library(fBasics)
library(tseries)
library(plot3D)
library(reshape2)
library(gridExtra)

source('setup.R')
```

# 02 - Spectral Analysis

## Yields of Interest Rate Futures

```{r, fig.height=6}
for(i in cYieldLobs[-1]){
  series <- termSt[, i, with=FALSE]
  seriesName <- colnames(series)
  plotData <- getSpectrumPlotData(series, title=seriesName)
  print(plotSpectrum(plotData))
  # file naming
  m <- regexpr("^(\\d+)Y", names(termSt)[i])
  n <- tolower(regmatches(names(termSt)[i], m))
  ggsaveHalfPage(paste0("spec_yield_", n, ".png"))
}
```

## First Differences of Yields

```{r, fig.height=6}
for(i in cYieldDiff[-1]){
  series <- termSt[, i, with=FALSE]
  seriesName <- colnames(series)
  plotData <- getSpectrumPlotData(series, title=seriesName)
  print(plotSpectrum(plotData))
  # file naming
  m <- regexpr("^(\\d+)Y", names(termSt)[i])
  n <- tolower(regmatches(names(termSt)[i], m))
  ggsaveHalfPage(paste0("spec_diff_yield_", n, ".png"))
}
```

## Realised Variances of Yields of Interest Rate Futures

```{r, fig.height=6}
for(i in cYieldRV[-1]){
  series <- termSt[, i, with=FALSE]
  seriesName <- names(series)
  plotData <- getSpectrumPlotData(series, title=seriesName)
  print(plotSpectrum(plotData))
  # file naming
  m <- regexpr("^(\\d+)Y", seriesName)
  n <- tolower(regmatches(seriesName, m))
  ggsaveHalfPage(paste0("spec_yield_rv_", n, ".png"))
}
```

## Realised Variances of Beta Estimates of the DNSM

```{r, fig.height=6}
for(i in cBetaRV[-1]){
  series <- termSt[, i, with=FALSE]
  seriesName <- names(series)
  plotData <- getSpectrumPlotData(series, title=seriesName)
  print(plotSpectrum(plotData))
  m <- regexpr("^(Beta\\d+)", names(series))
  n <- tolower(regmatches(names(series), m))
  ggsaveHalfPage(paste0("spec_", n, "_rv.png"))
}
```

## First Differences of Beta Coefficients

```{r, fig.height=6}
for(i in cBetaDiff[-1]){
  series <- termSt[, i, with=FALSE]
  seriesName <- colnames(series)
  plotData <- getSpectrumPlotData(series, title=seriesName)
  print(plotSpectrum(plotData))
  m <- regexpr("^(Beta\\d+)", names(series))
  n <- tolower(regmatches(names(series), m))
  ggsaveHalfPage(paste0("spec_", n, "_diff.png"))
}
```

## Yields - Moving Windows

```{r, fig.height=6}
for(i in cYieldLobs[-1]){
  series <- termSt[, i, with=FALSE]
  plotData <- getSWSpectrumPlotData(series, names(series), win.length=125)
  print(plotSWSpectrum(plotData, 'spectogram', dates=termSt[, timestamp]))
  m <- regexpr("^(\\d+)Y", names(series))
  n <- tolower(regmatches(names(series), m))
  ggsaveHalfPage(paste0("spectogram_yield_", n, ".png"))
  print(plotSWSpectrum(plotData, 'samples-quants'))
  # plotSWSpectrum(plotData, 'samples-spectra')
  # plotSWSpectrum(plotData, 'pvals')
}
```

## Beta Coefficients of DNSM - Moving Windows

```{r, fig.height=6}
for(i in cBetaLobs[-1]){
  series <- termSt[, i, with=FALSE]
  plotData <- getSWSpectrumPlotData(series, names(series), win.length=125)
  print(plotSWSpectrum(plotData, 'spectogram', dates=termSt[, timestamp]))
  m <- regexpr("^(\\d+)Y", names(series))
  n <- tolower(regmatches(names(series), m))
  # print(plotSWSpectrum(plotData, 'samples-quants'))
  # plotSWSpectrum(plotData, 'samples-spectra')
  # plotSWSpectrum(plotData, 'pvals')
}
```
